### ISSUE TITLE
[Bug]: 启动后卡住不动

### ISSUE THREAD

**Issue by hongyu1314** [RockChinQ/QChatGPT#376]
### 部署方式

安装器部署

### 系统环境

windows10

### Python环境

Python 3.10.9

### 异常情况

配置完mirai且正常登陆后运行run-bot.bat卡住不动，qchatgpt运行到加载pkg.openai.manager模块时后面的代码好像就跳过了
![ZLO_O{MIG{RTVAF({T`@9`A](https://user-images.githubusercontent.com/129932100/229998181-5d7e0f96-2066-4558-b634-f3bf37a01439.png)
![K5E`PJ K NI}N%KQK~66 5](https://user-images.githubusercontent.com/129932100/229997590-ae5cc623-a5b0-48f8-a9d3-73da8a586871.jpg)
![~~N6 C W3GN)T48Q5Z76EOY](https://user-images.githubusercontent.com/129932100/229997685-62c58f49-12a3-4380-9c77-c7f08fb44200.jpg)

![X)_)DEWH{ X2P@8LRU6JN05](https://user-images.githubusercontent.com/129932100/229997760-bfbdc54b-1350-4125-8e01-50aa726ad06c.jpg)

**Comment by Lq0ne** [comment]
实测已解决，回退python版本至3.9即可解决

**Comment by RockChinQ** [comment]
暂不清楚问题出在哪，初步怀疑是由于YiriMirai未适配最新的mah导致。将逐步排查并解决。在此之前请尝试更换Python版本（上方提到）、使用其他方式重新部署等解决方案。

**Comment by zzq1685554902** [comment]
C:\Users\ZZQ\anaconda3\python.exe D:\PH\pythonProject3\QChatGPT\main.py 
正在更新依赖库，请等待...
这个操作不是必须的,如果不想更新,请在config.py中将upgrade_dependencies设置为False
[2023-04-08 01:03:31.861] main.py (111) - [INFO] : 检查config模块完整性.
[2023-04-08 01:03:31.862] main.py (146) - [INFO] : 检查tips模块完整性.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.douban.com/simple/
Requirement already satisfied: openai in c:\users\zzq\anaconda3\lib\site-packages (0.27.2)
Requirement already satisfied: Pillow in c:\users\zzq\anaconda3\lib\site-packages (9.4.0)
Requirement already satisfied: aiohttp in c:\users\zzq\anaconda3\lib\site-packages (from openai) (3.8.4)
Requirement already satisfied: tqdm in c:\users\zzq\anaconda3\lib\site-packages (from openai) (4.64.1)
Requirement already satisfied: requests>=2.20 in c:\users\zzq\anaconda3\lib\site-packages (from openai) (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (2022.9.14)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (1.8.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (1.3.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (21.4.0)
Requirement already satisfied: colorama in c:\users\zzq\anaconda3\lib\site-packages (from tqdm->openai) (0.4.5)
[2023-04-08 01:03:39.326] utils.py (160) - [INFO] : NumExpr defaulting to 8 threads.
Database initialized.
[2023-04-08 01:03:40.075] keymgr.py (61) - [INFO] : 使用api-key:default
[2023-04-08 01:03:40.076] manager.py (30) - [INFO] : 文字总使用量：0
[2023-04-08 01:03:40.077] manager.py (86) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-04-08 01:03:40.077] host.py (89) - [INFO] : 加载插件
[2023-04-08 01:03:40.079] models.py (219) - [INFO] : 插件注册完成: n='加群审批', d='自动审批加群申请', v=0.1, a='RockChinQ' (<class 'plugins.auto_approval.main.AutoApproval'>)
[2023-04-08 01:03:40.081] host.py (81) - [INFO] : 加载模块: plugins/auto_approval/main.py 成功
[2023-04-08 01:03:40.082] models.py (219) - [INFO] : 插件注册完成: n='CmdCN', d='命令中文支持', v=0.1, a='RockChinQ' (<class 'plugins.cmdcn.cmdcn.CmdCnPlugin'>)
[2023-04-08 01:03:40.083] host.py (81) - [INFO] : 加载模块: plugins/cmdcn/cmdcn.py 成功
[2023-04-08 01:03:40.085] models.py (219) - [INFO] : 插件注册完成: n='Hello', d='hello world', v=0.1, a='RockChinQ' (<class 'plugins.hello_plugin.main.HelloPlugin'>)
[2023-04-08 01:03:40.085] host.py (81) - [INFO] : 加载模块: plugins/hello_plugin/main.py 成功
[2023-04-08 01:03:40.086] models.py (219) - [INFO] : 插件注册完成: n='啊对对对', d='你都这样了，我就顺从你吧', v=0.1, a='RockChinQ' (<class 'plugins.urlikethisijustsix.urlt.AdddPlugin'>)
[2023-04-08 01:03:40.087] host.py (81) - [INFO] : 加载模块: plugins/urlikethisijustsix/urlt.py 成功
[2023-04-08 01:03:40.087] host.py (106) - [INFO] : 初始化插件
[2023-04-08 01:03:40.087] host.py (114) - [INFO] : 插件 加群审批 已初始化
[2023-04-08 01:03:40.087] host.py (114) - [INFO] : 插件 CmdCN 已初始化
[2023-04-08 01:03:40.087] host.py (114) - [INFO] : 插件 Hello 已初始化
[2023-04-08 01:03:40.088] host.py (114) - [INFO] : 插件 啊对对对 已初始化
2023-04-08 01:03:40 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-04-08 01:03:40.090] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-04-08 01:03:42.095] main.py (306) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-04-08 01:03:54.103] main.py (312) - [INFO] : QQ: 366009314, MAH: 127.0.0.1:8080
[2023-04-08 01:03:54.103] main.py (313) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-04-08 01:04:00.321] main.py (341) - [INFO] : 新版本可用，请发送 !update 进行自动更新
更新日志:
v2.3.7 修复cfg指令失效问题
[2023-04-08 01:04:01.233] main.py (352) - [CRITICAL] : [公告] 2023/3/31 21:35 【插件兼容性问题】若您使用了revLibs插件，并将主程序升级到了v2.3.0，请立即使用管理员账号向机器人账号发送!plugin update命令更新逆向库插件，以解决由于情景预设重构引起的兼容性问题。（后面就没有输出了）
h

**Comment by RockChinQ** [comment]
> C:\Users\ZZQ\anaconda3\python.exe D:\PH\pythonProject3\QChatGPT\main.py 正在更新依赖库，请等待... 这个操作不是必须的,如果不想更新,请在config.py中将upgrade_dependencies设置为False [2023-04-08 01:03:31.861] main.py (111) - [INFO] : 检查config模块完整性. [2023-04-08 01:03:31.862] main.py (146) - [INFO] : 检查tips模块完整性. WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip. Please see [pypa/pip#5599](https://github.com/pypa/pip/issues/5599) for advice on fixing the underlying issue. To avoid this problem you can invoke Python with '-m pip' instead of running pip directly. Looking in indexes: https://pypi.douban.com/simple/ Requirement already satisfied: openai in c:\users\zzq\anaconda3\lib\site-packages (0.27.2) Requirement already satisfied: Pillow in c:\users\zzq\anaconda3\lib\site-packages (9.4.0) Requirement already satisfied: aiohttp in c:\users\zzq\anaconda3\lib\site-packages (from openai) (3.8.4) Requirement already satisfied: tqdm in c:\users\zzq\anaconda3\lib\site-packages (from openai) (4.64.1) Requirement already satisfied: requests>=2.20 in c:\users\zzq\anaconda3\lib\site-packages (from openai) (2.28.2) Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (2.0.4) Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (1.26.11) Requirement already satisfied: idna<4,>=2.5 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (3.3) Requirement already satisfied: certifi>=2017.4.17 in c:\users\zzq\anaconda3\lib\site-packages (from requests>=2.20->openai) (2022.9.14) Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (6.0.4) Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (4.0.2) Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (1.8.2) Requirement already satisfied: aiosignal>=1.1.2 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (1.3.1) Requirement already satisfied: frozenlist>=1.1.1 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (1.3.3) Requirement already satisfied: attrs>=17.3.0 in c:\users\zzq\anaconda3\lib\site-packages (from aiohttp->openai) (21.4.0) Requirement already satisfied: colorama in c:\users\zzq\anaconda3\lib\site-packages (from tqdm->openai) (0.4.5) [2023-04-08 01:03:39.326] utils.py (160) - [INFO] : NumExpr defaulting to 8 threads. Database initialized. [2023-04-08 01:03:40.075] keymgr.py (61) - [INFO] : 使用api-key:default [2023-04-08 01:03:40.076] manager.py (30) - [INFO] : 文字总使用量：0 [2023-04-08 01:03:40.077] manager.py (86) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829] [2023-04-08 01:03:40.077] host.py (89) - [INFO] : 加载插件 [2023-04-08 01:03:40.079] models.py (219) - [INFO] : 插件注册完成: n='加群审批', d='自动审批加群申请', v=0.1, a='RockChinQ' (<class 'plugins.auto_approval.main.AutoApproval'>) [2023-04-08 01:03:40.081] host.py (81) - [INFO] : 加载模块: plugins/auto_approval/main.py 成功 [2023-04-08 01:03:40.082] models.py (219) - [INFO] : 插件注册完成: n='CmdCN', d='命令中文支持', v=0.1, a='RockChinQ' (<class 'plugins.cmdcn.cmdcn.CmdCnPlugin'>) [2023-04-08 01:03:40.083] host.py (81) - [INFO] : 加载模块: plugins/cmdcn/cmdcn.py 成功 [2023-04-08 01:03:40.085] models.py (219) - [INFO] : 插件注册完成: n='Hello', d='hello world', v=0.1, a='RockChinQ' (<class 'plugins.hello_plugin.main.HelloPlugin'>) [2023-04-08 01:03:40.085] host.py (81) - [INFO] : 加载模块: plugins/hello_plugin/main.py 成功 [2023-04-08 01:03:40.086] models.py (219) - [INFO] : 插件注册完成: n='啊对对对', d='你都这样了，我就顺从你吧', v=0.1, a='RockChinQ' (<class 'plugins.urlikethisijustsix.urlt.AdddPlugin'>) [2023-04-08 01:03:40.087] host.py (81) - [INFO] : 加载模块: plugins/urlikethisijustsix/urlt.py 成功 [2023-04-08 01:03:40.087] host.py (106) - [INFO] : 初始化插件 [2023-04-08 01:03:40.087] host.py (114) - [INFO] : 插件 加群审批 已初始化 [2023-04-08 01:03:40.087] host.py (114) - [INFO] : 插件 CmdCN 已初始化 [2023-04-08 01:03:40.087] host.py (114) - [INFO] : 插件 Hello 已初始化 [2023-04-08 01:03:40.088] host.py (114) - [INFO] : 插件 啊对对对 已初始化 2023-04-08 01:03:40 - WARNING 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-04-08 01:03:40.090] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-04-08 01:03:42.095] main.py (306) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。 [2023-04-08 01:03:54.103] main.py (312) - [INFO] : QQ: 366009314, MAH: 127.0.0.1:8080 [2023-04-08 01:03:54.103] main.py (313) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 #37 [2023-04-08 01:04:00.321] main.py (341) - [INFO] : 新版本可用，请发送 !update 进行自动更新 更新日志: v2.3.7 修复cfg指令失效问题 [2023-04-08 01:04:01.233] main.py (352) - [CRITICAL] : [公告] 2023/3/31 21:35 【插件兼容性问题】若您使用了revLibs插件，并将主程序升级到了v2.3.0，请立即使用管理员账号向机器人账号发送!plugin update命令更新逆向库插件，以解决由于情景预设重构引起的兼容性问题。（后面就没有输出了） h

#37

**Comment by RockChinQ** [comment]
近期将通过NoneBot2框架接入go-cqhttp，请关注 #423
